name: Lint and Format

on:
    pull_request:
        branches: [develop]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: 🛒 Checkout code
              uses: actions/checkout@v3

            - name: 📂 Filter paths
              id: filter
              uses: dorny/paths-filter@v2
              with:
                  filters: |
                      js:
                        - '**/*.js'
                        - '**/*.mjs'

            - name: 🛫 Set up Node.js
              if: steps.filter.outputs.js == 'true'
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: 📄 Install ESLint
              if: steps.filter.outputs.js == 'true'
              run: |
                  npm init -y
                  npm install eslint eslint-config-standard eslint-plugin-html eslint-plugin-jsdoc eslint-plugin-security

            - name: Create ESLint config
              if: steps.filter.outputs.js == 'true'
              run: |
                  echo "{
                      \"extends\": \"standard\",
                      \"env\": {
                          \"browser\": true,
                          \"worker\": true,
                          \"es2021\": true
                      },
                      \"parserOptions\": {
                          \"ecmaVersion\": 2021,
                          \"sourceType\": \"module\"
                      },
                      \"plugins\": [\"html\", \"jsdoc\", \"security\"],
                      \"rules\": {
                          \"semi\": [\"error\", \"always\"],
                          \"quotes\": [\"error\", \"single\"],
                          \"eqeqeq\": \"error\",
                          \"no-var\": \"error\",
                          \"prefer-const\": \"error\",
                          \"curly\": \"error\",
                          \"no-unused-vars\": [\"error\"],
                          \"indent\": [\"error\", 4],
                          \"keyword-spacing\": [\"error\", { \"before\": true, \"after\": true }],
                          \"object-curly-spacing\": [\"error\", \"always\"],
                          \"no-console\": [\"warn\", { \"allow\": [\"warn\", \"error\"] }],
                          \"no-alert\": \"warn\",
                          \"max-len\": [\"warn\", { \"code\": 100 }],
                          \"jsdoc/require-jsdoc\": [
                              \"warn\",
                              {
                                  \"require\": {
                                      \"FunctionDeclaration\": true,
                                      \"ClassDeclaration\": true,
                                      \"MethodDefinition\": true
                                  }
                              }
                          ]
                      }
                  }" > .eslintrc.json


            - name: Run ESLint
              if: steps.filter.outputs.js == 'true'
              run: npx eslint "**/*.{js,mjs}" 