name: Lint

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            js: ['**/*.js', '**/*.mjs']
            css: ['**/*.css']

      - name: Set up Node.js
        if: steps.filter.outputs.js == 'true' || steps.filter.outputs.css == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install linters
        if: steps.filter.outputs.js == 'true' || steps.filter.outputs.css == 'true'
        run: npm install --global stylelint stylelint-config-standard eslint

      - name: Run stylelint
        if: steps.filter.outputs.css == 'true'
        run: stylelint "**/*.css"

      - name: Run eslint
        if: steps.filter.outputs.js == 'true'
        run: eslint "**/*.{js,mjs}"
