name: Lint

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v3

      - name: 📂 Filter paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            js: ['**/*.js', '**/*.mjs']

      - name: 🛫 Set up Node.js
        if: steps.filter.outputs.js == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📄 Install linters
        if: steps.filter.outputs.js == 'true'
        run: npm install eslint eslint-config-standard

      - name: Create ESLint config
        run: |
          echo "module.exports = { \"extends\": \"standard\" };" > .eslintrc.js

      - name: Run ESLint
        if: steps.filter.outputs.js == 'true'
        run: npx eslint "**/*.{js,mjs}